name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, github-runner]   # use the label you gave your runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pip install pytest
          pytest || echo "No tests yet"

      - name: Build Docker image
        run: docker build -t github-actions-demo:latest .
        env:
          DOCKER_BUILDKIT: 1   # optional, faster builds
